name: Sync To Gitee

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

concurrency:
  group: git-mirror

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:GuizhanCraft/SlimefunWarfare-CN.git"
          destination-repo: "git@gitee.com:ybw0014/SlimefunWarfare-CN.git"
